### ISSUE TITLE
Abalaorios bug xD

### ISSUE THREAD

**Issue by Danilomilo** [RoDNet/Bugtracker-Infinium-4.0.6a#692]
Abalorio  [Furia de Forjainquina] el cd de este abalaorio es de dos minutos pero cuando lo uso no puedo volver a usarlo en unos 5 min o mas, parece como si tuviera un cd interno q dura mas de 2min 

Abalaorio  [Corazón de ira] este abalaorio cuando se activa se reinicia muchas veces, seria bueno q le coloquen un cd interno xD ....

**Comment by redneo** [comment]
http://es.wowhead.com/item=59461#english-comments puesto el cd a 120 segundos. 

http://es.wowhead.com/item=59224 y su otra versión tienen un 10% de posibilidades de que salte cada 90 segundos como dice en un comentario:
how the hell can this be a BiS item... with 10% proc and 90 sec ICD... Seems to me that the only reason this is a BiS item is only because of the Expertise.
